// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ojk63YVTOLXDmEROmWdt5H3eJKrDm-g',
    appId: '1:24131452118:web:0c6424ea3c2f2b8016dd77',
    messagingSenderId: '24131452118',
    projectId: 'stocknote-7b4d5',
    authDomain: 'stocknote-7b4d5.firebaseapp.com',
    storageBucket: 'stocknote-7b4d5.firebasestorage.app',
    measurementId: 'G-JXEHKCB4D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDISsyVNAKUqMnIba550-03PrUit2Mu4Wg',
    appId: '1:24131452118:android:1f8614f1c54568e516dd77',
    messagingSenderId: '24131452118',
    projectId: 'stocknote-7b4d5',
    storageBucket: 'stocknote-7b4d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXn_5ed9r2shAGuIRuMI9qYiQmWlKgRQ0',
    appId: '1:24131452118:ios:17120033414b2d6716dd77',
    messagingSenderId: '24131452118',
    projectId: 'stocknote-7b4d5',
    storageBucket: 'stocknote-7b4d5.firebasestorage.app',
    iosBundleId: 'com.example.aiChart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXn_5ed9r2shAGuIRuMI9qYiQmWlKgRQ0',
    appId: '1:24131452118:ios:17120033414b2d6716dd77',
    messagingSenderId: '24131452118',
    projectId: 'stocknote-7b4d5',
    storageBucket: 'stocknote-7b4d5.firebasestorage.app',
    iosBundleId: 'com.example.aiChart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ojk63YVTOLXDmEROmWdt5H3eJKrDm-g',
    appId: '1:24131452118:web:8244dcfe3692a4fa16dd77',
    messagingSenderId: '24131452118',
    projectId: 'stocknote-7b4d5',
    authDomain: 'stocknote-7b4d5.firebaseapp.com',
    storageBucket: 'stocknote-7b4d5.firebasestorage.app',
    measurementId: 'G-HWCK15VJMW',
  );
}
